import type { Project } from "@/types/project";

export const PROJECTS: Project[] = [
  {
    coord: "01",
    year: "2024",
    title: "SpeechEase",
    tag: "Cloud Computing · Mobile Application",
    role: "Cloud Computing Cohort",
    desc: "A personalized speech learning platform that leverages Google Cloud services and machine learning technologies to deliver scalable speech practice experiences. The project features cloud-based backend services, secure authentication, and efficient data processing designed for reliability and performance.",
    stack: ["Google Cloud", "Node.js", "Express.js", "Flask"],
    image: "/projects/speechease.webp",
    github: "https://github.com/bangkit-speechease",
    demo: "https://www.linkedin.com/posts/william-susilo_lifeatbangkit-bangkit24h2-bepchallenge-activity-7280584122278785025-AdLt?utm_source=share&utm_medium=member_desktop&rcm=ACoAAEXlWXoBHpYySyYDHGHKxovHahlnzoFY7IA",
    featured: true,
  },

  {
    coord: "02",
    year: "2024",
    title: "planT",
    tag: "Mobile Application · Agriculture",
    role: "Mobile Developer",
    desc: "A smart farming application designed to help small-scale farmers and home gardeners monitor plant growth, receive personalized recommendations, and improve cultivation outcomes through data-driven insights.",
    stack: ["Flutter", "Dart", "Firebase"],
    image: "/projects/plant.webp",
    github: "https://github.com/WilliamSusilo/planT",
    demo: "https://www.youtube.com/watch?v=kF_1hrlI8rI",
    featured: true,
  },

  {
    coord: "03",
    year: "2024",
    title: "Piru Application",
    tag: "Web Application · Booking System",
    role: "Full Stack Developer",
    desc: "A room booking management system developed for student organizations to simplify room reservations, approval workflows, and scheduling processes through a centralized web platform.",
    stack: ["PHP", "MySQL", "JavaScript", "HTML", "CSS"],
    image: "/projects/piru.webp",
    github: "https://github.com/WilliamSusilo/Piru-Application",
    featured: true,
  },

  {
    coord: "04",
    year: "2024",
    title: "NotedGo",
    tag: "Web Application · Productivity",
    role: "Full Stack Developer",
    desc: "A mood-based note-taking platform that combines habit tracking, mood monitoring, and productivity features to help users better understand their daily activities and emotional patterns.",
    stack: ["PHP", "MySQL", "Tailwind CSS", "JavaScript"],
    image: "/projects/notedgo.webp",
    github: "https://github.com/WilliamSusilo/NotedGo",
    featured: true,
  },

  {
    coord: "05",
    year: "2023",
    title: "To Do List App",
    tag: "Mobile Application · Productivity",
    role: "Mobile Developer",
    desc: "A task management application featuring user authentication, calendar integration, and task organization capabilities to improve personal productivity and activity planning.",
    stack: ["Flutter", "Dart", "SQLite"],
    image: "/projects/todolist.webp",
    github: "https://github.com/WilliamSusilo/To-Do-List-App",
    featured: false,
  },

  {
    coord: "06",
    year: "2023",
    title: "Student Recording System",
    tag: "Information System · Education",
    role: "Backend Developer",
    desc: "A student administration system that manages academic records through complete CRUD operations, supporting efficient data management and reporting processes.",
    stack: ["PHP", "MySQL", "JavaScript"],
    image: "/projects/student-recording.webp",
    github: "https://github.com/WilliamSusilo/Student-Recording-System",
    featured: false,
  },

  {
    coord: "07",
    year: "2023",
    title: "Library's Helper App",
    tag: "Desktop Application · Library Management",
    role: "Python Developer",
    desc: "A library management application that streamlines borrowing and returning workflows while providing search capabilities and secure administrative tools for library staff.",
    stack: ["Python"],
    image: "/projects/library-helper.webp",
    github: "https://github.com/WilliamSusilo/Library-s-Helper-App",
    featured: false,
  },

  {
    coord: "08",
    year: "2022",
    title: "Personal Website",
    tag: "Portfolio · Web Development",
    role: "Frontend Developer",
    desc: "A personal portfolio website developed using vanilla web technologies to showcase projects, certifications, achievements, technical skills, and professional experiences.",
    stack: ["HTML", "CSS", "JavaScript"],
    image: "/projects/personal-website.webp",
    github: "https://github.com/WilliamSusilo/Personal-Website",
    featured: false,
  },
];
